"""Generates guest stub libraries and host thunk wrappers for refract_native.

Outputs (relative to native/):
  guest/gen/<lib>.S            ARM64 stub library sources (one per HLE library)
  src/gen/vulkan_thunks.inc    typed host wrappers for every Vulkan command

Stub layout (16 bytes each): movz x16, #index ; svc #lib_id ; ret ; nop.
The library's constructor registers its name table with the host (svc #2).

usage: python gen_thunks.py [--vk vk.xml]
"""
import argparse
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

HERE = Path(__file__).resolve().parent
NATIVE = HERE.parent
EXTERNAL = NATIVE.parent.parent / "external" / "src"

# Must match src/thunks.h
LIB_IDS = {
    "libvulkan.so": 0x10,
    "libandroid.so": 0x12,
    "librefract_jni.so": 0x13,
    "libEGL.so": 0x14,
    "libGLESv3.so": 0x15,
    "libaaudio.so": 0x16,
    "libOpenSLES.so": 0x17,
    "libnativewindow.so": 0x18,
    "librefract_host.so": 0x19,
    "libovrplatformloader.so": 0x1A,
    "libmediandk.so": 0x1B,
    "libGLESv1_CM.so": 0x1C,
    "libGLESv2.so": 0x1D,
    "libcamera2ndk.so": 0x1E,
    "libjnigraphics.so": 0x1F,
    "libsync.so": 0x20,
    "libbinder_ndk.so": 0x21,
    "libamidi.so": 0x22,
}

# Platforms whose Vulkan commands make no sense for an Android guest.
FOREIGN_PLATFORMS = {"xlib", "xlib_xrandr", "xcb", "wayland", "directfb", "win32", "vi", "ios", "macos",
                     "metal", "fuchsia", "ggp", "screen", "sci", "provisional", "ohos"}
# Hand-written in src/vulkan_hle.cpp (not generated).
VK_SPECIAL = {
    "vkGetInstanceProcAddr", "vkGetDeviceProcAddr", "vkCreateInstance", "vkDestroyInstance",
    "vkEnumerateInstanceExtensionProperties", "vkEnumerateDeviceExtensionProperties",
    "vkCreateDevice", "vkCreateAndroidSurfaceKHR", "vkCreateDebugUtilsMessengerEXT",
    "vkDestroyDebugUtilsMessengerEXT", "vkCreateDebugReportCallbackEXT",
    "vkDestroyDebugReportCallbackEXT", "vkGetAndroidHardwareBufferPropertiesANDROID",
    "vkGetMemoryAndroidHardwareBufferANDROID", "vkEnumerateInstanceLayerProperties",
    "vkEnumerateDeviceLayerProperties", "vkGetPhysicalDeviceProperties",
    "vkGetPhysicalDeviceProperties2", "vkGetPhysicalDeviceProperties2KHR",
}


def write_if_changed(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return
    path.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {path.relative_to(NATIVE)}")


def stub_source(soname: str, names: list[str], extra: str = "") -> str:
    lib_id = LIB_IDS[soname]
    out = [f"// Generated by tools/gen_thunks.py: guest stub library {soname}.",
           "    .text",
           "    .p2align 4",
           "__refract_stubs:"]
    for i, name in enumerate(names):
        out += [f"    .globl {name}",
                f"    .type {name}, %function",
                f"{name}:",
                f"    movz x16, #{i}",
                f"    svc #{lib_id:#x}",
                "    ret",
                "    nop",
                f"    .size {name}, 16"]
    out += ["",
            "    .p2align 2",
            "__refract_register:",
            f"    mov x0, #{lib_id:#x}",
            "    adrp x1, __refract_names",
            "    add x1, x1, :lo12:__refract_names",
            "    adrp x2, __refract_stubs",
            "    add x2, x2, :lo12:__refract_stubs",
            f"    movz x3, #{len(names) & 0xffff}",
            f"    movk x3, #{len(names) >> 16}, lsl #16",
            "    svc #2",
            "    ret",
            "",
            "    .section .init_array, \"aw\", %init_array",
            "    .p2align 3",
            "    .quad __refract_register",
            "",
            "    .section .data.rel.ro, \"aw\"",
            "    .p2align 3",
            "__refract_names:"]
    out += [f"    .quad .Lname{i}" for i in range(len(names))]
    out += ["", "    .section .rodata.str1.1, \"aMS\", %progbits, 1"]
    for i, name in enumerate(names):
        out += [f".Lname{i}:", f"    .asciz \"{name}\""]
    out.append(extra)
    out.append("    .section .note.GNU-stack, \"\", %progbits")
    return "\n".join(out) + "\n"


# --- registry parsing ----------------------------------------------------------

class Command:
    def __init__(self, name, ret, params, alias=None):
        self.name, self.ret, self.params, self.alias = name, ret, params, alias


def param_decl(param: ET.Element) -> tuple[str, str]:
    """Returns (C type, name) for a <param>, with arrays decayed to pointers."""
    text = "".join(param.itertext()).strip()
    text = re.sub(r"\s+", " ", text)
    name = param.find("name").text
    arr = re.search(r"\[.*\]", text)
    text = re.sub(r"\[.*\]", "", text).strip()
    ctype = text[: text.rfind(name)].strip()
    if arr:
        ctype += "*"
    return ctype, name


def parse_commands(root: ET.Element, api_attr: str | None) -> dict[str, Command]:
    cmds: dict[str, Command] = {}
    aliases = []
    for c in (c for cs in root.findall("commands") for c in cs.findall("command")):
        api = c.get("api")
        if api_attr and api and api_attr not in api.split(","):
            continue
        if c.get("alias"):
            aliases.append((c.get("name"), c.get("alias")))
            continue
        proto = c.find("proto")
        name = proto.find("name").text
        ret = "".join(proto.itertext()).strip()
        ret = ret[: ret.rfind(name)].strip()
        params = []
        for p in c.findall("param"):
            if api_attr and p.get("api") and api_attr not in p.get("api").split(","):
                continue
            params.append(param_decl(p))
        cmds[name] = Command(name, ret, params)
    for name, target in aliases:
        if target in cmds:
            t = cmds[target]
            cmds[name] = Command(name, t.ret, t.params, alias=target)
    return cmds


def foreign_commands(root: ET.Element, foreign: set[str]) -> set[str]:
    out = set()
    for ext in root.find("extensions").findall("extension"):
        disabled = ext.get("supported") == "disabled"
        if not disabled and ext.get("platform") not in foreign:
            continue
        for req in ext.findall("require"):
            for c in req.findall("command"):
                out.add(c.get("name"))
    return out


def vulkan(vk_xml: Path) -> list[str]:
    root = ET.parse(vk_xml).getroot()
    cmds = parse_commands(root, "vulkan")
    # Commands only reachable through foreign-platform or disabled extensions.
    skip = foreign_commands(root, FOREIGN_PLATFORMS)
    # Keep anything also required by a core feature or a non-foreign extension.
    keep = set()
    for feat in root.findall("feature"):
        if "vulkan" not in (feat.get("api") or "vulkan").split(","):
            continue
        for req in feat.findall("require"):
            for c in req.findall("command"):
                keep.add(c.get("name"))
    for ext in root.find("extensions").findall("extension"):
        if ext.get("supported") == "disabled" or ext.get("platform") not in (None, "android"):
            continue
        if "vulkan" not in (ext.get("supported") or "vulkan").split(","):
            continue
        for req in ext.findall("require"):
            for c in req.findall("command"):
                keep.add(c.get("name"))
    names = sorted(n for n in cmds if n in keep or n not in skip)
    names = [n for n in names if n in keep]

    lines = ["// Generated by tools/gen_thunks.py from vk.xml. Typed wrappers that forward",
             "// guest Vulkan calls to the host loader. Allocation callbacks are guest code,",
             "// so they are never passed to the host driver.",
             ""]
    table = []
    for i, n in enumerate(names):
        c = cmds[n]
        if n in VK_SPECIAL:
            continue
        sig = ", ".join(f"{t} {p}" for t, p in c.params)
        args = ", ".join("nullptr" if t == "const VkAllocationCallbacks*" else p for t, p in c.params)
        ret = c.ret
        resolve = "VkResolveGlobal" if c.params and c.params[0][0] not in (
            "VkInstance", "VkPhysicalDevice", "VkDevice", "VkQueue", "VkCommandBuffer") else "VkResolve"
        if n in ("vkEnumerateInstanceVersion",):
            resolve = "VkResolveGlobal"
        lines.append(f"static {ret} VkT_{n}({sig}) {{")
        lines.append(f"    static auto pfn = reinterpret_cast<PFN_{c.alias or n}>({resolve}(\"{n}\"));")
        if ret == "void":
            lines.append(f"    if (pfn) pfn({args});")
        else:
            lines.append(f"    if (!pfn) return {{}};")
            lines.append(f"    return pfn({args});")
        lines.append("}")
        table.append(f"    {{\"{n}\", &Wrap<&VkT_{n}>}},")
    lines += ["", "static void AddGeneratedVulkanThunks(std::map<std::string, ThunkFn>& m) {",
              "    const std::pair<const char*, ThunkFn> kEntries[] = {"]
    lines += table
    lines += ["    };", "    for (const auto& [name, fn] : kEntries)", "        m[name] = fn;", "}", ""]
    write_if_changed(NATIVE / "src" / "gen" / "vulkan_thunks.inc", "\n".join(lines))
    write_if_changed(NATIVE / "guest" / "gen" / "libvulkan.S", stub_source("libvulkan.so", names))
    return names


def name_list_lib(soname: str, list_file: Path) -> None:
    """List entries: "name[@VER]" (function) or "data:name:size[@VER]" (zeroed object)."""
    funcs, data, versions = [], [], {}
    for line in list_file.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or line.startswith("__cfi"):
            continue  # the linker rejects a __cfi_check that isn't page aligned
        ver = None
        if "@" in line:
            line, ver = line.split("@", 1)
        if line.startswith("data:"):
            _, name, size = line.split(":")
            data.append((name, int(size)))
        else:
            name = line
            funcs.append(name)
        versions.setdefault(ver, []).append(name)
    extra = []
    if data:
        extra.append("    .data")
        for name, size in data:
            extra += ["    .p2align 4", f"    .globl {name}", f"    .type {name}, %object", f"{name}:",
                      f"    .zero {size}", f"    .size {name}, {size}"]
    stem = Path(soname).stem
    write_if_changed(NATIVE / "guest" / "gen" / (stem + ".S"), stub_source(soname, funcs, "\n".join(extra)))
    if any(v for v in versions):
        # Unversioned exports join the first version node (an anonymous node can't be
        # mixed with named ones); unversioned references still bind to them.
        script = []
        unversioned = versions.get(None, [])
        for ver, names in versions.items():
            if ver is None:
                continue
            names = names + unversioned
            unversioned = []
            script.append(ver + " {\n  global:\n" + "".join(f"    {n};\n" for n in names) + "};\n")
        write_if_changed(NATIVE / "guest" / "gen" / (stem + ".map"), "".join(script))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--vk", type=Path, default=EXTERNAL / "Vulkan-Headers" / "registry" / "vk.xml")
    args = ap.parse_args()
    vk = vulkan(args.vk)
    for lst in sorted((NATIVE / "guest" / "lists").glob("*.txt")):
        name_list_lib(lst.stem + ".so", lst)
    print(f"vulkan: {len(vk)} commands")
    return 0


if __name__ == "__main__":
    sys.exit(main())
