# Auto-generated by digitalis/scripts/build-and-package-prebuilts.sh — do not edit.
#
# Binary-only Digitalis (ARM64->x86_64) translator for an x86_64 host product.
# Drop this tree into your tree (e.g. vendor/digitalis/prebuilts/) and add to your
# x86_64 product .mk:
#
#   $(call inherit-product, vendor/digitalis/prebuilts/digitalis-prebuilts.mk)
#
# Provides the translator + proxy libs + ARM64 guest libs + configs only; the
# consuming product supplies the rest of the x86_64 system (and, for Vulkan, the
# GFXStream/ANGLE GPU stack).

LOCAL_PATH := $(call my-dir)

# Native-bridge enablement (mirrors frameworks/libs/binary_translation/enable_arm64_to_x86_64.mk).
PRODUCT_SYSTEM_PROPERTIES += \
    ro.dalvik.vm.native.bridge=libberberis_arm64.so \
    ro.dalvik.vm.isa.arm64=x86_64 \
    ro.enable.native.bridge.exec=1

# Copy every prebuilt artifact into the system image at its canonical path.
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/bin/arm64/app_process64:system/bin/arm64/app_process64
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/bin/arm64/linker64:system/bin/arm64/linker64
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/bin/berberis_program_runner_binfmt_misc_arm64:system/bin/berberis_program_runner_binfmt_misc_arm64
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/bin/berberis_program_runner_arm64:system/bin/berberis_program_runner_arm64
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/etc/binfmt_misc/arm64_dyn:system/etc/binfmt_misc/arm64_dyn
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/etc/binfmt_misc/arm64_exe:system/etc/binfmt_misc/arm64_exe
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/etc/init/berberis.rc:system/etc/init/berberis.rc
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/etc/ld.config.arm64.txt:system/etc/ld.config.arm64.txt
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/libberberis_arm64.so:system/lib64/libberberis_arm64.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/libberberis_exec_region.so:system/lib64/libberberis_exec_region.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/libberberis_proxy_libEGL.so:system/lib64/libberberis_proxy_libEGL.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/libberberis_proxy_libGLESv1_CM.so:system/lib64/libberberis_proxy_libGLESv1_CM.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/libberberis_proxy_libGLESv2.so:system/lib64/libberberis_proxy_libGLESv2.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/libberberis_proxy_libGLESv3.so:system/lib64/libberberis_proxy_libGLESv3.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/libberberis_proxy_libOpenMAXAL.so:system/lib64/libberberis_proxy_libOpenMAXAL.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/libberberis_proxy_libOpenSLES.so:system/lib64/libberberis_proxy_libOpenSLES.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/libberberis_proxy_libaaudio.so:system/lib64/libberberis_proxy_libaaudio.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/libberberis_proxy_libamidi.so:system/lib64/libberberis_proxy_libamidi.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/libberberis_proxy_libandroid.so:system/lib64/libberberis_proxy_libandroid.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/libberberis_proxy_libandroid_runtime.so:system/lib64/libberberis_proxy_libandroid_runtime.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/libberberis_proxy_libbinder_ndk.so:system/lib64/libberberis_proxy_libbinder_ndk.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/libberberis_proxy_libc.so:system/lib64/libberberis_proxy_libc.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/libberberis_proxy_libcamera2ndk.so:system/lib64/libberberis_proxy_libcamera2ndk.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/libberberis_proxy_libjnigraphics.so:system/lib64/libberberis_proxy_libjnigraphics.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/libberberis_proxy_libm.so:system/lib64/libberberis_proxy_libm.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/libberberis_proxy_libmediandk.so:system/lib64/libberberis_proxy_libmediandk.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/libberberis_proxy_libnativehelper.so:system/lib64/libberberis_proxy_libnativehelper.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/libberberis_proxy_libnativewindow.so:system/lib64/libberberis_proxy_libnativewindow.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/libberberis_proxy_libneuralnetworks.so:system/lib64/libberberis_proxy_libneuralnetworks.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/libberberis_proxy_libvulkan.so:system/lib64/libberberis_proxy_libvulkan.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/libberberis_proxy_libwebviewchromium_plat_support.so:system/lib64/libberberis_proxy_libwebviewchromium_plat_support.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/ld-android.so:system/lib64/arm64/ld-android.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libEGL.so:system/lib64/arm64/libEGL.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libGLESv1_CM.so:system/lib64/arm64/libGLESv1_CM.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libGLESv2.so:system/lib64/arm64/libGLESv2.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libGLESv3.so:system/lib64/arm64/libGLESv3.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libOpenMAXAL.so:system/lib64/arm64/libOpenMAXAL.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libOpenSLES.so:system/lib64/arm64/libOpenSLES.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libaaudio.so:system/lib64/arm64/libaaudio.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libamidi.so:system/lib64/arm64/libamidi.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libandroid.so:system/lib64/arm64/libandroid.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libandroid_runtime.so:system/lib64/arm64/libandroid_runtime.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libandroidicu.so:system/lib64/arm64/libandroidicu.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libbase.so:system/lib64/arm64/libbase.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libbinder_ndk.so:system/lib64/arm64/libbinder_ndk.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libc++.so:system/lib64/arm64/libc++.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libc.so:system/lib64/arm64/libc.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libcamera2ndk.so:system/lib64/arm64/libcamera2ndk.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libcompiler_rt.so:system/lib64/arm64/libcompiler_rt.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libcrypto.so:system/lib64/arm64/libcrypto.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libcutils.so:system/lib64/arm64/libcutils.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libdl.so:system/lib64/arm64/libdl.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libdl_android.so:system/lib64/arm64/libdl_android.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libgui.so:system/lib64/arm64/libgui.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libicu.so:system/lib64/arm64/libicu.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libicui18n.so:system/lib64/arm64/libicui18n.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libicuuc.so:system/lib64/arm64/libicuuc.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libjnigraphics.so:system/lib64/arm64/libjnigraphics.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/liblog.so:system/lib64/arm64/liblog.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libm.so:system/lib64/arm64/libm.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libmediandk.so:system/lib64/arm64/libmediandk.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libnative_bridge_vdso.so:system/lib64/arm64/libnative_bridge_vdso.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libnativehelper.so:system/lib64/arm64/libnativehelper.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libnativewindow.so:system/lib64/arm64/libnativewindow.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libneuralnetworks.so:system/lib64/arm64/libneuralnetworks.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libsqlite.so:system/lib64/arm64/libsqlite.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libssl.so:system/lib64/arm64/libssl.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libstdc++.so:system/lib64/arm64/libstdc++.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libsync.so:system/lib64/arm64/libsync.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libutils.so:system/lib64/arm64/libutils.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libvndksupport.so:system/lib64/arm64/libvndksupport.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libvulkan.so:system/lib64/arm64/libvulkan.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libwebviewchromium_plat_support.so:system/lib64/arm64/libwebviewchromium_plat_support.so
PRODUCT_COPY_FILES += $(LOCAL_PATH)/system/lib64/arm64/libz.so:system/lib64/arm64/libz.so

# Allow these artifacts to live on /system.
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/bin/arm64/app_process64
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/bin/arm64/linker64
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/bin/berberis_program_runner_binfmt_misc_arm64
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/bin/berberis_program_runner_arm64
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/etc/binfmt_misc/arm64_dyn
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/etc/binfmt_misc/arm64_exe
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/etc/init/berberis.rc
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/etc/ld.config.arm64.txt
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/libberberis_arm64.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/libberberis_exec_region.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/libberberis_proxy_libEGL.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/libberberis_proxy_libGLESv1_CM.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/libberberis_proxy_libGLESv2.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/libberberis_proxy_libGLESv3.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/libberberis_proxy_libOpenMAXAL.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/libberberis_proxy_libOpenSLES.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/libberberis_proxy_libaaudio.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/libberberis_proxy_libamidi.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/libberberis_proxy_libandroid.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/libberberis_proxy_libandroid_runtime.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/libberberis_proxy_libbinder_ndk.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/libberberis_proxy_libc.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/libberberis_proxy_libcamera2ndk.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/libberberis_proxy_libjnigraphics.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/libberberis_proxy_libm.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/libberberis_proxy_libmediandk.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/libberberis_proxy_libnativehelper.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/libberberis_proxy_libnativewindow.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/libberberis_proxy_libneuralnetworks.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/libberberis_proxy_libvulkan.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/libberberis_proxy_libwebviewchromium_plat_support.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/ld-android.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libEGL.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libGLESv1_CM.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libGLESv2.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libGLESv3.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libOpenMAXAL.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libOpenSLES.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libaaudio.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libamidi.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libandroid.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libandroid_runtime.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libandroidicu.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libbase.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libbinder_ndk.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libc++.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libc.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libcamera2ndk.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libcompiler_rt.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libcrypto.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libcutils.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libdl.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libdl_android.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libgui.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libicu.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libicui18n.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libicuuc.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libjnigraphics.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/liblog.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libm.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libmediandk.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libnative_bridge_vdso.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libnativehelper.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libnativewindow.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libneuralnetworks.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libsqlite.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libssl.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libstdc++.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libsync.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libutils.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libvndksupport.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libvulkan.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libwebviewchromium_plat_support.so
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST += system/lib64/arm64/libz.so
